name: 'OIDC Debugger'
description: 'Print the GitHub Actions OIDC claims.'
inputs:
  audience:
    description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.audience }}
